/**
 * Extracts the <style> block from each Phase 1 mockup and rewrites every
 * selector so it only applies beneath that page's root class.
 *
 * Why: the five mockups were authored as standalone documents. They reuse
 * class names (.opt, .tgl, .comp, .rail, .wrap) with DIFFERENT rules, and
 * several redefine the same custom properties with different values
 * (--surface-page, --text-primary, --border). Vite bundles all CSS into one
 * stylesheet, so without scoping the later page silently restyles the earlier
 * one. Scoping :root onto the page wrapper keeps each page's token values
 * intact because the wrapper is an ancestor of everything on that page.
 */
import fs from 'node:fs';
import path from 'node:path';
import postcss from 'postcss';
import prefixer from 'postcss-prefix-selector';

const SRC = new URL('../mockups', import.meta.url).pathname;
const OUT = new URL('../src/pages', import.meta.url).pathname;

const PAGES = [
  { file: '1-landing-page.html',          name: 'LandingPage',   scope: 'pg-landing'  },
  { file: '2-search-results-tiers.html',  name: 'SearchResults', scope: 'pg-results'  },
  { file: '3-preset-package-detail.html', name: 'PackageDetail', scope: 'pg-detail'   },
  { file: '4-custom-builder.html',        name: 'PackageBuilder',scope: 'pg-builder'  },
  { file: '5-checkout-review.html',       name: 'Checkout',      scope: 'pg-checkout' },
];

// Selectors that target the document itself. Inside a scoped page these must
// collapse onto the page wrapper rather than escape to the real <html>/<body>.
const DOC_SELECTORS = new Set([':root', 'html', 'body']);

fs.mkdirSync(OUT, { recursive: true });

for (const page of PAGES) {
  const html = fs.readFileSync(path.join(SRC, page.file), 'utf8');

  const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  if (!styleMatch) throw new Error(`No <style> block found in ${page.file}`);

  const prefix = `.${page.scope}`;

  const result = postcss([
    prefixer({
      prefix,
      transform(pfx, selector, prefixedSelector) {
        const s = selector.trim();

        // :root / html / body -> the page wrapper itself
        if (DOC_SELECTORS.has(s)) return pfx;

        // "body .thing" -> ".pg-x .thing"
        if (/^(body|html)\s+/.test(s)) return s.replace(/^(body|html)\s+/, `${pfx} `);

        // "*" -> ".pg-x, .pg-x *" so the reset covers the wrapper too
        if (s === '*') return `${pfx}, ${pfx} *`;

        return prefixedSelector;
      },
    }),
  ]).process(styleMatch[1], { from: undefined });

  const banner =
    `/* ${page.name} — styles ported verbatim from ${page.file}.\n` +
    `   Every selector is scoped to ${prefix} so the five screens can share one\n` +
    `   bundle without overwriting each other's class names or token values.\n` +
    `   Generated by tools/scope-css.mjs — edit the values here, not the mockup. */\n\n`;

  const outPath = path.join(OUT, `${page.name}.css`);
  fs.writeFileSync(outPath, banner + result.css.trim() + '\n');
  console.log(`${page.name.padEnd(15)} -> ${path.basename(outPath)}  (${result.css.length} bytes)`);
}
